version: 2

models:

  # Dimensions
  - name: dim_customer
    description: "Dimension table for customers"
    columns:
      - name: customer_id
        description: "Customer ID"
        tests:
          - not_null
          - unique
      - name: first_name
        tests:
          - not_null
      - name: last_name
        tests:
          - not_null
      - name: full_name
        tests:
          - not_null
      - name: phone
      - name: email
      - name: street
      - name: city
      - name: state
      - name: zip_code

  - name: dim_product
    description: "Dimension table for products with brand and category"
    columns:
      - name: product_id
        description: "Product ID"
        tests:
          - not_null
          - unique
      - name: product_name
      - name: model_year
      - name: list_price
      - name: brand_name
      - name: category_name

  - name: dim_order_status
    description: "Dimension table for order status"
    columns:
      - name: order_status_id
        tests:
          - not_null
      - name: order_status_name

  - name: dim_store
    description: "Dimension table for stores"
    columns:
      - name: store_id
        description: "Store ID"
        tests:
          - not_null
          - unique
      - name: store_name
      - name: phone
      - name: email
      - name: street
      - name: city
      - name: state
      - name: zip_code

  - name: dim_staff
    description: "Dimension table for staff"
    columns:
      - name: staff_id
        description: "Staff ID"
        tests:
          - not_null
          - unique
      - name: first_name
      - name: last_name
      - name: email
      - name: phone
      - name: active
      - name: store_id
        tests:
          - not_null
      - name: manager_id

  - name: dim_date
    description: "Dimension table for dates"
    columns:
      - name: date_id
        description: "Unique date key"
        tests:
          - not_null
          - unique
      - name: full_date
        tests:
          - is_date_format
      - name: year
      - name: month
      - name: day
      - name: week
      - name: day_of_year
      - name: weekday_name
      - name: is_weekend
      - name: quarter

  # Fact table
  - name: fact_sales
    description: "Fact table for sales orders"
    columns:
      - name: order_id
        description: "Order ID"
        tests:
          - not_null
      - name: customer_id
        description: "Customer ID"
        tests:
          - not_null
          - relationships:
              to: ref('dim_customer')
              field: customer_id
      - name: store_id
        description: "Store ID"
        tests:
          - relationships:
              to: ref('dim_store')
              field: store_id
      - name: staff_id
        description: "Staff ID"
        tests:
          - relationships:
              to: ref('dim_staff')
              field: staff_id
      - name: product_id
        description: "Product ID"
        tests:
          - relationships:
              to: ref('dim_product')
              field: product_id
      - name: order_date_id
      - name: shipped_date_id
      - name: required_date_id
      - name: quantity
        tests:
          - checkgte0
      - name: list_price
        tests:
          - checkgte0
      - name: discount
      - name: total_amount
        tests:
          - checkgte0
      - name: discount_amount
        tests:
          - checkgte0
      - name: shipping_delay
